#!/usr/bin/env python3
"""
Generate SQL inserts for `public.employee_location_assignments` from a Connecteam-style Users CSV.

Safety:
- Reads CSV from an arbitrary local path (outside the repo is fine).
- Writes SQL to a repo-local output path (suggest: out/employee_location_assignments.sql).
- Does NOT print any PII (names/emails/phones) to stdout.

What it does:
- Finds store tokens in the CSV's `Store` and `Groups` columns.
- Treats numeric tokens like "118" as store numbers -> looks up `public.locations.slug = 'store-118'`.
- Treats a small set of known special store labels (e.g. "HQ", "Lama Wholesale") as name-based lookups.
- Skips non-store group labels ("All users group", roles like "Cashier", etc.).
- Emits SQL that resolves employees by `employees.email` and locations by slug or name, then inserts rows.

Notes:
- Employees with blank email are skipped (no reliable match).
- If an email doesn't exist in `public.employees`, the insert becomes a no-op (safe).
"""

from __future__ import annotations

import argparse
import csv
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional


SPECIAL_STORE_LABELS = {
    "hq": "HQ",
    "hq--time clock": "HQ--Time Clock",
    "lama wholesale": "Lama Wholesale",
    "irish isle provisions": "Irish Isle Provisions",
    "pot of gold beer distributor": "Pot of Gold Beer Distributor",
    # QT29 appears in the stores list; treat as name-based.
    "qt29": "QT29",
}

# Common non-store group labels that appear in `Groups`
IGNORE_GROUP_TOKENS = {
    "all users group",
    "field visit",
    "field visitor",
    "manager",
    "assistant manager",
    "shift lead",
    "cashier",
    "cooks",
    "cook",
    "deli cook",
    "food manager",
    "supervisor",
    "admin",
    "hr",
    "office manager",
    "operation analyst",
    "specialist",
}


def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "").strip()).lower()


def split_tokens(raw: str) -> list[str]:
    if not raw:
        return []
    # CSV field uses commas as separators; some tokens may have extra whitespace.
    return [t.strip() for t in raw.split(",") if t.strip()]


def extract_store_keys(store_field: str, groups_field: str) -> set[str]:
    """
    Returns a set of store keys:
    - "store-118" for numeric store numbers
    - "name:HQ" etc for special labels
    """
    out: set[str] = set()

    for tok in split_tokens(store_field):
        k = _norm(tok)
        if not k:
            continue
        if k.isdigit():
            out.add(f"store-{k}")
            continue
        if k in SPECIAL_STORE_LABELS:
            out.add(f"name:{SPECIAL_STORE_LABELS[k]}")

    for tok in split_tokens(groups_field):
        k = _norm(tok)
        if not k or k in IGNORE_GROUP_TOKENS:
            continue
        # Some group lists include pure store numbers.
        if k.isdigit():
            out.add(f"store-{k}")
            continue
        if k in SPECIAL_STORE_LABELS:
            out.add(f"name:{SPECIAL_STORE_LABELS[k]}")

    return out


@dataclass(frozen=True)
class Row:
    email: str
    store_keys: tuple[str, ...]


def iter_rows(csv_path: Path) -> Iterable[Row]:
    with csv_path.open("r", newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for r in reader:
            email = (r.get("Email") or "").strip()
            if not email:
                continue
            store = r.get("Store") or ""
            groups = r.get("Groups") or ""
            keys = sorted(extract_store_keys(store, groups))
            if not keys:
                continue
            yield Row(email=email, store_keys=tuple(keys))


def sql_escape_literal(s: str) -> str:
    return s.replace("'", "''")


def render_sql(rows: list[Row]) -> str:
    lines: list[str] = []
    lines.append("-- Generated by scripts/import/employee_location_assignments_from_connecteam_csv.py")
    lines.append("-- Safe to run multiple times (uses ON CONFLICT DO NOTHING).")
    lines.append("")
    lines.append("begin;")
    lines.append("")

    total_pairs = 0
    for row in rows:
        email_lit = sql_escape_literal(row.email.lower())
        for key in row.store_keys:
            total_pairs += 1
            if key.startswith("store-"):
                slug = key
                slug_lit = sql_escape_literal(slug)
                lines.append(
                    "insert into public.employee_location_assignments (employee_id, location_id, note)\n"
                    "select e.id, l.id, 'import: connecteam users csv'\n"
                    "from public.employees e\n"
                    "join public.locations l on l.slug = '{slug}'\n"
                    "where e.email is not null and lower(e.email) = '{email}'\n"
                    "on conflict (employee_id, location_id) do nothing;\n".format(
                        slug=slug_lit, email=email_lit
                    )
                )
            elif key.startswith("name:"):
                name = key.split(":", 1)[1]
                name_lit = sql_escape_literal(name)
                # Use ILIKE for robustness ("HQ" vs "HQ--Time Clock").
                lines.append(
                    "insert into public.employee_location_assignments (employee_id, location_id, note)\n"
                    "select e.id, l.id, 'import: connecteam users csv'\n"
                    "from public.employees e\n"
                    "join public.locations l on l.name ilike '{name}%'\n"
                    "where e.email is not null and lower(e.email) = '{email}'\n"
                    "on conflict (employee_id, location_id) do nothing;\n".format(
                        name=name_lit, email=email_lit
                    )
                )

    lines.append("")
    lines.append("commit;")
    lines.append("")
    lines.append(f"-- Summary: generated {len(rows)} employee rows, {total_pairs} assignment inserts.")
    return "\n".join(lines)


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--csv",
        required=True,
        help="Path to Connecteam Users CSV (e.g. ~/Downloads/users (9)(Sheet1).csv)",
    )
    ap.add_argument(
        "--out",
        default="out/employee_location_assignments.sql",
        help="Output SQL path (default: out/employee_location_assignments.sql)",
    )
    args = ap.parse_args(argv)

    csv_path = Path(args.csv).expanduser()
    out_path = Path(args.out).expanduser()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    rows = list(iter_rows(csv_path))
    sql = render_sql(rows)
    out_path.write_text(sql, encoding="utf-8")

    # Print only non-PII counts.
    print(f"Wrote SQL: {out_path} (rows={len(rows)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

